apiVersion: v1
kind: Service
metadata:
  name: shopease-backend
  namespace: shopease
  labels:
    app: shopease-backend
spec:
  selector:
    app: shopease-backend
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  type: ClusterIP
