# IMPORTANT: Replace all values with base64-encoded strings
# Encode: echo -n "your-value" | base64
#
# Do NOT commit real secrets to version control.
# In production, use AWS Secrets Manager or Kubernetes External Secrets.

apiVersion: v1
kind: Secret
metadata:
  name: shopease-secrets
  namespace: shopease
type: Opaque
data:
  # echo -n "jdbc:postgresql://your-rds-host:5432/shopease" | base64
  SPRING_DATASOURCE_URL:      amRiYzpwb3N0Z3Jlc3FsOi8vbG9jYWxob3N0OjU0MzIvc2hvcGVhc2U=

  # echo -n "shopuser" | base64
  SPRING_DATASOURCE_USERNAME: c2hvcHVzZXI=

  # echo -n "shoppass" | base64
  SPRING_DATASOURCE_PASSWORD: c2hvcHBhc3M=

  # echo -n "your-256-bit-jwt-secret" | base64
  JWT_SECRET:                 NDA0RTYzNTI2NjU1NkE1ODZFMzI3MjM1NzUzODc4MkY0MTNGNDQyODQ3MkI0QjYyNTA2NDUzNjc1NjZCNTk3MA==

  # echo -n "replace-me" | base64
  AWS_ACCESS_KEY:             cmVwbGFjZS1tZQ==

  # echo -n "replace-me" | base64
  AWS_SECRET_KEY:             cmVwbGFjZS1tZQ==
