apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: shopease
  labels:
    app: postgres
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
  # ClusterIP — only accessible inside the cluster
  type: ClusterIP
